language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install python-coveralls
script:
  - py.test run_test.py --cov-report=term-missing --cov=opensearch
after_success:
  - coveralls