language: python
python:
  - "2.7"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install python-coveralls
script:
  - py.test run_test.py --cov-report=term-missing --cov=opensearch