language: python
python:
  - "2.7"
install:
  - pip install pytest
  - pip install pytest-cov
script:
  - py.test test/test_const.py
  - py.test test/test_document.py
  - py.test test/test_push_doc.py
  - py.test test/test_search.py